import { Library, Status } from "./helpers";

/*
Add your library here or make any adjustments to libraries here!

If you know of a library having App Subscriptions or not feel free to add by

appSubscriptions: (status)

Statuses include:

Status.Yes - Does support
Status.No - Does not support
Status.Partial - Partial Support
Status.PR - Has a PR (best done with an array of Status.PR and the link)
Status.InDev - Feature is in the development version
Status.PartialDev - There is partial support in the development version

*/

export const libs: Library[] = [
	{
		name: 'Concord',
		url: 'https://github.com/Cogmasters/concord',
		language: 'C',
		apiVer: 10,
		gwVer: 10,
		slashCommands: Status.Yes,
		buttons: Status.Yes,
		selectMenus: Status.Partial,
		threads: Status.Yes,
		guildStickers: Status.Yes,
		contextMenus: Status.Yes,
		autocomplete: Status.Yes,
		scheduledEvents: Status.Yes,
		timeouts: Status.Yes,
		modals: Status.Yes,
		permsv2: Status.Yes,
		automod: Status.Yes,
		localization: Status.Yes,
		forums: Status.Partial,
	},
	{
		name: 'Orca',
		url: 'https://github.com/cee-studio/orca',
		language: 'C',
		apiVer: 9,
		gwVer: 9,
		slashCommands: Status.Yes,
		buttons: Status.Yes,
		selectMenus: Status.Partial,
		threads: Status.Yes,
		guildStickers: Status.No,
		contextMenus: Status.Yes,
		autocomplete: Status.No,
		scheduledEvents: Status.No,
		timeouts: Status.No,
		modals: Status.No,
		permsv2: Status.No,
		automod: Status.No,
		localization: Status.No,
		forums: Status.No
	},
	{
		name: 'DisCatSharp',
		url: 'https://github.com/Aiko-IT-Systems/DisCatSharp',
		language: 'C#',
		apiVer: 10,
		gwVer: 10,
		slashCommands: Status.Yes,
		buttons: Status.Yes,
		selectMenus: Status.Yes,
		threads: Status.Yes,
		guildStickers: Status.Yes,
		contextMenus: Status.Yes,
		autocomplete: Status.Yes,
		scheduledEvents: Status.Yes,
		timeouts: Status.Yes,
		modals: Status.Yes,
		permsv2: Status.Yes,
		automod: Status.Yes,
		localization: Status.Yes,
		forums: Status.Yes
	},
	{
		name: 'Discord.Net',
		url: 'https://github.com/discord-net/Discord.Net',
		language: 'C#',
		apiVer: 10,
		gwVer: 10,
		slashCommands: Status.Yes,
		buttons: Status.Yes,
		selectMenus: Status.Yes,
		threads: Status.Yes,
		guildStickers: Status.Yes,
		contextMenus: Status.Yes,
		autocomplete: Status.Yes,
		scheduledEvents: Status.Yes,
		timeouts: Status.Yes,
		modals: Status.Yes,
		permsv2: Status.Yes,
		automod: Status.Yes,
		localization: Status.Yes,
		forums: Status.Yes
	},
	{
		name: 'Disqord',
		url: 'https://github.com/Quahu/Disqord',
		language: 'C#',
		apiVer: 10,
		gwVer: 10,
		slashCommands: Status.Yes,
		buttons: Status.Yes,
		selectMenus: Status.Yes,
		threads: Status.Yes,
		guildStickers: Status.Yes,
		contextMenus: Status.Yes,
		autocomplete: Status.Yes,
		scheduledEvents: Status.Yes,
		timeouts: Status.Yes,
		modals: Status.Yes,
		permsv2: Status.Yes,
		automod: Status.Yes,
		localization: Status.Yes,
		forums: Status.Yes,
		appSubscriptions: Status.No
	},
	{
		name: 'DSharpPlus',
		url: 'https://github.com/DSharpPlus/DSharpPlus',
		language: 'C#',
		apiVer: 10,
		gwVer: 10,
		slashCommands: Status.Yes,
		buttons: Status.Yes,
		selectMenus: Status.Yes,
		threads: Status.Yes,
		guildStickers: Status.Yes,
		contextMenus: Status.Yes,
		autocomplete: Status.Yes,
		scheduledEvents: Status.Yes,
		timeouts: Status.Yes,
		modals: Status.Yes,
		permsv2: Status.Yes,
		automod: Status.Yes,
		localization: Status.Yes,
		forums: Status.Yes
	},
	{
		name: 'NetCord',
		url: 'https://github.com/KubaZ2/NetCord',
		language: 'C#',
		apiVer: 10,
		gwVer: 10,
		slashCommands: Status.Yes,
		buttons: Status.Yes,
		selectMenus: Status.Yes,
		threads: Status.Yes,
		guildStickers: Status.Yes,
		contextMenus: Status.Yes,
		autocomplete: Status.Yes,
		scheduledEvents: Status.Yes,
		timeouts: Status.Yes,
		modals: Status.Yes,
		permsv2: Status.Yes,
		automod: Status.Yes,
		localization: Status.Yes,
		forums: Status.Yes
	},
	{
		name: 'Remora.Discord',
		url: 'https://github.com/Remora/Remora.Discord',
		language: 'C#',
		apiVer: 10,
		gwVer: 10,
		slashCommands: Status.Yes,
		buttons: Status.Yes,
		selectMenus: Status.Yes,
		threads: Status.Yes,
		guildStickers: Status.Yes,
		contextMenus: Status.Yes,
		autocomplete: Status.Yes,
		scheduledEvents: Status.Yes,
		timeouts: Status.Yes,
		modals: Status.Yes,
		permsv2: Status.Yes,
		automod: Status.Yes,
		localization: Status.Yes,
		forums: Status.Yes
	},
	{
		name: 'aegis.cpp 🪦',
		url: 'https://github.com/zeroxs/aegis.cpp',
		language: 'C++',
		apiVer: 6,
		gwVer: 6,
		slashCommands: Status.No,
		buttons: Status.No,
		selectMenus: Status.No,
		threads: Status.No,
		guildStickers: Status.No,
		contextMenus: Status.No,
		autocomplete: Status.No,
		scheduledEvents: Status.No,
		timeouts: Status.No,
		modals: Status.No,
		permsv2: Status.No,
		automod: Status.No,
		localization: Status.No,
		forums: Status.No
	},
	{
		name: 'D++',
		url: 'https://github.com/brainboxdotcc/DPP',
		language: 'C++',
		apiVer: 10,
		gwVer: 10,
		slashCommands: Status.Yes,
		buttons: Status.Yes,
		selectMenus: Status.Yes,
		threads: Status.Yes,
		guildStickers: Status.Yes,
		contextMenus: Status.Yes,
		autocomplete: Status.Yes,
		scheduledEvents: Status.Yes,
		timeouts: Status.Yes,
		modals: Status.Yes,
		permsv2: Status.Yes,
		automod: Status.Yes,
		localization: Status.Yes,
		forums: Status.Yes
	},
	{
		name: 'Discord++',
		url: 'https://github.com/DiscordPP/discordpp',
		language: 'C++',
		apiVer: 9,
		gwVer: 9,
		slashCommands: Status.Yes,
		buttons: Status.Yes,
		selectMenus: Status.Partial,
		threads: Status.Yes,
		guildStickers: Status.Yes,
		contextMenus: Status.Yes,
		autocomplete: Status.No,
		scheduledEvents: Status.No,
		timeouts: Status.No,
		modals: Status.No,
		permsv2: Status.No,
		automod: Status.No,
		localization: Status.No,
		forums: Status.No
	},
	{
		name: 'DiscordCoreAPI',
		url: 'https://github.com/RealTimeChris/DiscordCoreAPI',
		language: 'C++',
		apiVer: 10,
		gwVer: 10,
		slashCommands: Status.Yes,
		buttons: Status.Yes,
		selectMenus: Status.Yes,
		threads: Status.Yes,
		guildStickers: Status.Yes,
		contextMenus: Status.Yes,
		autocomplete: Status.Yes,
		scheduledEvents: Status.Yes,
		timeouts: Status.Yes,
		modals: Status.Yes,
		permsv2: Status.Yes,
		automod: Status.Yes,
		localization: Status.Yes,
		forums: Status.Yes
	},
	{
		name: 'Sleepy Discord',
		url: 'https://github.com/yourWaifu/sleepy-discord',
		language: 'C++',
		apiVer: [8, 10],
		gwVer: [8, 10],
		slashCommands: Status.Yes,
		buttons: Status.Yes,
		selectMenus: Status.Partial,
		threads: Status.InDev,
		guildStickers: Status.No,
		contextMenus: Status.Yes,
		autocomplete: Status.Yes,
		scheduledEvents: Status.No,
		timeouts: Status.No,
		modals: Status.Yes,
		permsv2: Status.No,
		automod: Status.No,
		localization: Status.No,
		forums: Status.No
	},
	{
		name: 'discljord',
		url: 'https://github.com/discljord/discljord',
		language: 'Clojure',
		apiVer: 9,
		gwVer: 9,
		slashCommands: Status.Yes,
		buttons: Status.Yes,
		selectMenus: Status.Partial,
		threads: Status.Yes,
		guildStickers: Status.Yes,
		contextMenus: Status.Yes,
		autocomplete: Status.Yes,
		scheduledEvents: Status.No,
		timeouts: Status.No,
		modals: Status.No,
		permsv2: Status.No,
		automod: Status.No,
		localization: Status.No,
		forums: Status.No
	},
	{
		name: 'discordcr',
		url: 'https://github.com/shardlab/discordcr',
		language: 'Crystal',
		apiVer: 9,
		gwVer: 9,
		slashCommands: [Status.PR, "https://github.com/shardlab/discordcr/pull/31"],
		buttons: [Status.PR, "https://github.com/shardlab/discordcr/pull/31"],
		selectMenus: [Status.PR, "https://github.com/shardlab/discordcr/pull/31"],
		threads: Status.Yes,
		guildStickers: Status.No,
		contextMenus: [Status.PR, "https://github.com/shardlab/discordcr/pull/31"],
		autocomplete: [Status.PR, "https://github.com/shardlab/discordcr/pull/31"],
		scheduledEvents: [Status.PR, "https://github.com/shardlab/discordcr/pull/37"],
		timeouts: Status.No,
		modals: [Status.PR, "https://github.com/shardlab/discordcr/pull/31"],
		permsv2: [Status.PR, "https://github.com/shardlab/discordcr/pull/31"],
		automod: Status.No,
		localization: [Status.PR, "https://github.com/shardlab/discordcr/pull/31"],
		forums: Status.No
	},
	{
		name: 'Mineral',
		url: 'https://github.com/mineral-dart',
		language: 'Dart',
		apiVer: 10,
		gwVer: 10,
		slashCommands: Status.Yes,
		buttons: Status.Yes,
		selectMenus: Status.Yes,
		threads: Status.Yes,
		guildStickers: Status.Yes,
		contextMenus: Status.Yes,
		autocomplete: Status.No,
		scheduledEvents: Status.Yes,
		timeouts: Status.Yes,
		modals: Status.Yes,
		permsv2: Status.Yes,
		automod: Status.Partial,
		localization: Status.No,
		forums: Status.Yes
	},
	{
		name: 'nyxx',
		url: 'https://github.com/nyxx-discord/nyxx',
		language: 'Dart',
		apiVer: 10,
		gwVer: 10,
		slashCommands: Status.Yes,
		buttons: Status.Yes,
		selectMenus: Status.Yes,
		threads: Status.Yes,
		guildStickers: Status.Yes,
		contextMenus: Status.Yes,
		autocomplete: Status.Yes,
		scheduledEvents: Status.Yes,
		timeouts: Status.Yes,
		modals: Status.Yes,
		permsv2: Status.Yes,
		automod: Status.Yes,
		localization: Status.Yes,
		forums: Status.Yes
	},
	{
		name: 'coxir',
		url: 'https://github.com/satom99/coxir',
		language: 'Elixir',
		apiVer: 9,
		gwVer: 8,
		slashCommands: Status.No,
		buttons: Status.Yes,
		selectMenus: Status.No,
		threads: Status.No,
		guildStickers: Status.No,
		contextMenus: Status.No,
		autocomplete: Status.No,
		scheduledEvents: Status.No,
		timeouts: Status.No,
		modals: Status.No,
		permsv2: Status.No,
		automod: Status.No,
		localization: Status.No,
		forums: Status.No
	},
	{
		name: 'Nostrum',
		url: 'https://github.com/Kraigie/nostrum',
		language: 'Elixir',
		apiVer: 10,
		gwVer: 10,
		slashCommands: Status.Yes,
		buttons: Status.Yes,
		selectMenus: Status.Partial,
		threads: Status.Yes,
		guildStickers: Status.Yes,
		contextMenus: Status.Yes,
		autocomplete: Status.Yes,
		scheduledEvents: Status.Yes,
		timeouts: Status.Yes,
		modals: Status.Yes,
		permsv2: Status.No,
		automod: Status.No,
		localization: Status.No,
		forums: Status.Yes
	},
	{
		name: 'arikawa',
		url: 'https://github.com/diamondburned/arikawa',
		language: 'Go',
		apiVer: 9,
		gwVer: 9,
		slashCommands: Status.Yes,
		buttons: Status.Yes,
		selectMenus: Status.Partial,
		threads: Status.Yes,
		guildStickers: Status.Partial,
		contextMenus: Status.Yes,
		autocomplete: Status.Yes,
		scheduledEvents: Status.Yes,
		timeouts: Status.Yes,
		modals: Status.Yes,
		permsv2: Status.Yes,
		automod: Status.No,
		localization: Status.Yes,
		forums: Status.Yes
	},
	{
		name: 'DiscordGo',
		url: 'https://github.com/bwmarrin/discordgo',
		language: 'Go',
		apiVer: 9,
		gwVer: 9,
		slashCommands: Status.Yes,
		buttons: Status.Yes,
		selectMenus: Status.Yes,
		threads: Status.Yes,
		guildStickers: Status.Yes,
		contextMenus: Status.Yes,
		autocomplete: Status.Yes,
		scheduledEvents: Status.Yes,
		timeouts: Status.Yes,
		modals: Status.Yes,
		permsv2: Status.Yes,
		automod: Status.Yes,
		localization: Status.Yes,
		forums: Status.Yes
	},
	{
		name: 'disgo',
		url: 'https://github.com/DisgoOrg/disgo',
		language: 'Go',
		apiVer: 10,
		gwVer: 10,
		slashCommands: Status.Yes,
		buttons: Status.Yes,
		selectMenus: Status.Yes,
		threads: Status.Yes,
		guildStickers: Status.Yes,
		contextMenus: Status.Yes,
		autocomplete: Status.Yes,
		scheduledEvents: Status.Yes,
		timeouts: Status.Yes,
		modals: Status.Yes,
		permsv2: Status.Yes,
		automod: Status.Yes,
		localization: Status.Yes,
		forums: Status.Yes
	},
	{
		name: 'Disgord',
		url: 'https://github.com/andersfylling/disgord',
		language: 'Go',
		apiVer: 9,
		gwVer: 9,
		slashCommands: Status.Yes,
		buttons: Status.Yes,
		selectMenus: Status.Partial,
		threads: Status.Yes,
		guildStickers: Status.Yes,
		contextMenus: Status.Yes,
		autocomplete: Status.InDev,
		scheduledEvents: Status.Yes,
		timeouts: Status.Yes,
		modals: Status.InDev,
		permsv2: Status.Yes,
		automod: Status.No,
		localization: Status.Yes,
		forums: Status.No
	},
	{
		name: 'Postcord',
		url: 'https://github.com/Postcord/rest',
		language: 'Go',
		apiVer: 9,
		gwVer: null,
		slashCommands: Status.Yes,
		buttons: Status.Yes,
		selectMenus: Status.Partial,
		threads: Status.Yes,
		guildStickers: Status.Yes,
		contextMenus: Status.Yes,
		autocomplete: Status.Yes,
		scheduledEvents: Status.Yes,
		timeouts: Status.Yes,
		modals: Status.No,
		permsv2: Status.Yes,
		automod: Status.No,
		localization: Status.No,
		forums: Status.No
	},
	{
		name: 'Calamity',
		url: 'https://github.com/simmsb/calamity',
		language: 'Haskell',
		apiVer: 10,
		gwVer: 9,
		slashCommands: Status.Yes,
		buttons: Status.Yes,
		selectMenus: Status.Partial,
		threads: Status.No,
		guildStickers: Status.No,
		contextMenus: Status.No,
		autocomplete: Status.Yes,
		scheduledEvents: Status.No,
		timeouts: Status.No,
		modals: Status.Yes,
		permsv2: Status.No,
		automod: Status.No,
		localization: Status.No,
		forums: Status.Partial
	},
	{
		name: 'discord-haskell',
		url: 'https://github.com/aquarial/discord-haskell',
		language: 'Haskell',
		apiVer: 10,
		gwVer: 10,
		slashCommands: Status.Yes,
		buttons: Status.Yes,
		selectMenus: Status.Yes,
		threads: Status.Yes,
		guildStickers: Status.Yes,
		contextMenus: Status.Yes,
		autocomplete: Status.Yes,
		scheduledEvents: Status.Yes,
		timeouts: Status.Yes,
		modals: Status.Yes,
		permsv2: Status.Yes,
		automod: Status.No,
		localization: Status.Yes,
		forums: Status.No
	},
	{
		name: 'hxdiscord',
		url: 'https://github.com/FurretDev/hxdiscord',
		language: 'Haxe',
		apiVer: 10,
		gwVer: 10,
		slashCommands: Status.Yes,
		buttons: Status.Yes,
		selectMenus: Status.Yes,
		threads: Status.No,
		guildStickers: Status.No,
		contextMenus: Status.Yes,
		autocomplete: Status.No,
		scheduledEvents: Status.No,
		timeouts: Status.No,
		modals: Status.Yes,
		permsv2: Status.Yes,
		automod: Status.No,
		localization: Status.No,
		forums: Status.No
	},
	{
		name: 'Haxicord',
		url: 'https://github.com/RaidAndFade/Haxicord',
		language: 'Haxe',
		apiVer: 6,
		gwVer: 6,
		slashCommands: Status.No,
		buttons: Status.No,
		selectMenus: Status.No,
		threads: Status.No,
		guildStickers: Status.No,
		contextMenus: Status.No,
		autocomplete: Status.No,
		scheduledEvents: Status.No,
		timeouts: Status.No,
		modals: Status.No,
		permsv2: Status.No,
		automod: Status.No,
		localization: Status.No,
		forums: Status.No
	},
	{
		name: 'catnip 🪦',
		url: 'https://github.com/mewna/catnip',
		language: 'Java',
		apiVer: 9,
		gwVer: 9,
		slashCommands: Status.Yes,
		buttons: Status.Yes,
		selectMenus: Status.Partial,
		threads: Status.Yes,
		guildStickers: Status.No,
		contextMenus: Status.Yes,
		autocomplete: Status.No,
		scheduledEvents: [Status.PR, "https://github.com/mewna/catnip/pull/640"],
		timeouts: Status.No,
		modals: Status.No,
		permsv2: Status.No,
		automod: Status.No,
		localization: Status.No,
		forums: Status.No
	},
	{
		name: 'discord.jar',
		url: 'https://github.com/discord-jar/discord.jar',
		language: 'Java',
		apiVer: 10,
		gwVer: 10,
		slashCommands: Status.Yes,
		buttons: Status.Yes,
		selectMenus: Status.Yes,
		threads: Status.Yes,
		guildStickers: Status.Yes,
		contextMenus: Status.Yes,
		autocomplete: Status.Yes,
		scheduledEvents: Status.Yes,
		timeouts: Status.Yes,
		modals: Status.Yes,
		permsv2: Status.Yes,
		automod: Status.Yes,
		localization: Status.Yes,
		forums: Status.Yes
	},
	{
		name: 'Discord4J',
		url: 'https://github.com/Discord4J/Discord4J',
		language: 'Java',
		apiVer: [8, 9],
		gwVer: [8, 9],
		slashCommands: Status.Yes,
		buttons: Status.Yes,
		selectMenus: Status.Yes,
		threads: Status.Yes,
		guildStickers: Status.Yes,
		contextMenus: Status.Yes,
		autocomplete: Status.Yes,
		scheduledEvents: Status.Yes,
		timeouts: Status.Yes,
		modals: Status.Yes,
		permsv2: Status.No,
		automod: Status.Yes,
		localization: Status.No,
		forums: Status.Yes
	},
	{
		name: 'Javacord',
		url: 'https://github.com/Javacord/Javacord',
		language: 'Java',
		apiVer: 10,
		gwVer: 10,
		slashCommands: Status.Yes,
		buttons: Status.Yes,
		selectMenus: Status.Yes,
		threads: Status.Yes,
		guildStickers: Status.Yes,
		contextMenus: Status.Yes,
		autocomplete: Status.Yes,
		scheduledEvents: Status.No,
		timeouts: Status.Yes,
		modals: Status.Yes,
		permsv2: Status.Yes,
		automod: Status.No,
		localization: Status.Yes,
		forums: [Status.PR, "https://github.com/Javacord/Javacord/pull/1131"]
	},
	{
		name: 'JDA',
		url: 'https://github.com/discord-jda/JDA',
		language: 'Java',
		apiVer: 10,
		gwVer: 10,
		slashCommands: Status.Yes,
		buttons: Status.Yes,
		selectMenus: Status.Yes,
		threads: Status.Yes,
		guildStickers: Status.Yes,
		contextMenus: Status.Yes,
		autocomplete: Status.Yes,
		scheduledEvents: Status.Yes,
		timeouts: Status.Yes,
		modals: Status.Yes,
		permsv2: Status.Yes,
		automod: Status.Yes,
		localization: Status.Yes,
		forums: Status.Yes
	},
	{
		name: 'Biscuit',
		url: 'https://github.com/oasisjs/biscuit',
		language: 'JavaScript',
		apiVer: 10,
		gwVer: 10,
		slashCommands: Status.Yes,
		buttons: Status.Yes,
		selectMenus: Status.Partial,
		threads: Status.Yes,
		guildStickers: Status.Yes,
		contextMenus: Status.Yes,
		autocomplete: Status.Yes,
		scheduledEvents: Status.Yes,
		timeouts: Status.Yes,
		modals: Status.Yes,
		permsv2: Status.Yes,
		automod: Status.Yes,
		localization: Status.Yes,
		forums: Status.Yes
	},
	{
		name: 'Detritus',
		url: 'https://github.com/detritusjs/client',
		language: 'JavaScript',
		apiVer: 9,
		gwVer: 9,
		slashCommands: Status.Yes,
		buttons: Status.Yes,
		selectMenus: Status.Partial,
		threads: Status.Yes,
		guildStickers: Status.Yes,
		contextMenus: Status.Yes,
		autocomplete: Status.InDev,
		scheduledEvents: Status.No,
		timeouts: Status.No,
		modals: Status.InDev,
		permsv2: Status.InDev,
		automod: Status.No,
		localization: Status.No,
		forums: Status.No
	},
	{
		name: 'dfx',
		url: 'https://github.com/tim-smart/dfx',
		language: 'JavaScript',
		apiVer: 10,
		gwVer: 10,
		slashCommands: Status.Yes,
		buttons: Status.Yes,
		selectMenus: Status.Yes,
		threads: Status.Yes,
		guildStickers: Status.Yes,
		contextMenus: Status.Yes,
		autocomplete: Status.Yes,
		scheduledEvents: Status.Yes,
		timeouts: Status.Yes,
		modals: Status.Yes,
		permsv2: Status.Yes,
		automod: Status.Yes,
		localization: Status.Yes,
		forums: Status.Yes
	},
	{
		name: 'discord.js',
		url: 'https://github.com/discordjs/discord.js',
		language: 'JavaScript',
		apiVer: 10,
		gwVer: 10,
		slashCommands: Status.Yes,
		buttons: Status.Yes,
		selectMenus: Status.Yes,
		threads: Status.Yes,
		guildStickers: Status.Yes,
		contextMenus: Status.Yes,
		autocomplete: Status.Yes,
		scheduledEvents: Status.Yes,
		timeouts: Status.Yes,
		modals: Status.Yes,
		permsv2: Status.Yes,
		automod: Status.Yes,
		localization: Status.Yes,
		forums: Status.Yes,
		appSubscriptions: [Status.PR, 'https://github.com/discordjs/discord.js/pull/9907']
	},
	{
		name: 'Discordeno',
		url: 'https://github.com/discordeno/discordeno',
		language: 'JavaScript',
		apiVer: 10,
		gwVer: 10,
		slashCommands: Status.Yes,
		buttons: Status.Yes,
		selectMenus: Status.Yes,
		threads: Status.Yes,
		guildStickers: Status.Yes,
		contextMenus: Status.Yes,
		autocomplete: Status.Yes,
		scheduledEvents: Status.Yes,
		timeouts: Status.Yes,
		modals: Status.Yes,
		permsv2: Status.Yes,
		automod: Status.Yes,
		localization: Status.Yes,
		forums: Status.Yes
	},
	{
		name: 'droff',
		url: 'https://github.com/tim-smart/droff',
		language: 'JavaScript',
		apiVer: 10,
		gwVer: 10,
		slashCommands: Status.Yes,
		buttons: Status.Yes,
		selectMenus: Status.Yes,
		threads: Status.Yes,
		guildStickers: Status.Yes,
		contextMenus: Status.Yes,
		autocomplete: Status.Yes,
		scheduledEvents: Status.Yes,
		timeouts: Status.Yes,
		modals: Status.Yes,
		permsv2: Status.Yes,
		automod: Status.Yes,
		localization: Status.Yes,
		forums: Status.Yes
	},
	{
		name: 'Dysnomia 🍴',
		url: 'https://github.com/projectdysnomia/dysnomia',
		language: 'JavaScript',
		apiVer: 10,
		gwVer: 10,
		slashCommands: Status.Yes,
		buttons: Status.Yes,
		selectMenus: Status.Yes,
		threads: Status.Yes,
		guildStickers: Status.Yes,
		contextMenus: Status.Yes,
		autocomplete: Status.Yes,
		scheduledEvents: Status.Yes,
		timeouts: Status.Yes,
		modals: Status.Yes,
		permsv2: Status.Yes,
		automod: Status.Yes,
		localization: Status.Yes,
		forums: Status.Yes
	},
	{
		name: 'Eris',
		url: 'https://github.com/abalabahaha/eris',
		language: 'JavaScript',
		apiVer: 9,
		gwVer: 9,
		slashCommands: Status.Yes,
		buttons: Status.Yes,
		selectMenus: Status.Partial,
		threads: Status.Yes,
		guildStickers: Status.Yes,
		contextMenus: Status.Yes,
		autocomplete: Status.Yes,
		scheduledEvents: Status.Yes,
		timeouts: Status.Yes,
		modals: [Status.PR, "https://github.com/abalabahaha/eris/pull/1432"],
		permsv2: [Status.PR, "https://github.com/abalabahaha/eris/pull/1372"],
		automod: [Status.PR, "https://github.com/abalabahaha/eris/pull/1428"],
		localization: Status.No,
		forums: Status.No
	},
	{
		name: 'Harmony',
		url: 'https://github.com/harmonyland/harmony',
		language: 'JavaScript',
		apiVer: 9,
		gwVer: 9,
		slashCommands: Status.Yes,
		buttons: Status.Yes,
		selectMenus: Status.Partial,
		threads: Status.Yes,
		guildStickers: Status.Yes,
		contextMenus: Status.Yes,
		autocomplete: Status.Yes,
		scheduledEvents: Status.No,
		timeouts: Status.Yes,
		modals: Status.Yes,
		permsv2: Status.No,
		automod: Status.No,
		localization: Status.No,
		forums: Status.Yes
	},
	{
		name: 'Oceanic',
		url: 'https://github.com/OceanicJS/Oceanic',
		language: 'JavaScript',
		apiVer: 10,
		gwVer: 10,
		slashCommands: Status.Yes,
		buttons: Status.Yes,
		selectMenus: Status.Yes,
		threads: Status.Yes,
		guildStickers: Status.Yes,
		contextMenus: Status.Yes,
		autocomplete: Status.Yes,
		scheduledEvents: Status.Yes,
		timeouts: Status.Yes,
		modals: Status.Yes,
		permsv2: Status.Yes,
		automod: Status.Yes,
		localization: Status.Yes,
		forums: Status.Yes
	},
	{
		name: 'SnowTransfer',
		url: 'https://github.com/DasWolke/SnowTransfer',
		language: 'JavaScript',
		apiVer: 10,
		gwVer: null,
		slashCommands: Status.Yes,
		buttons: Status.Yes,
		selectMenus: Status.Partial,
		threads: Status.Yes,
		guildStickers: Status.Yes,
		contextMenus: Status.Yes,
		autocomplete: Status.Yes,
		scheduledEvents: Status.Yes,
		timeouts: Status.Yes,
		modals: Status.Yes,
		permsv2: Status.Yes,
		automod: Status.No,
		localization: Status.Yes,
		forums: Status.No
	},
	{
		name: 'Tiscord',
		url: 'https://github.com/tiscordlib/tiscord',
		language: 'JavaScript',
		apiVer: 10,
		gwVer: 10,
		slashCommands: Status.Yes,
		buttons: Status.Yes,
		selectMenus: Status.Partial,
		threads: Status.Yes,
		guildStickers: Status.Yes,
		contextMenus: Status.Yes,
		autocomplete: Status.No,
		scheduledEvents: Status.No,
		timeouts: Status.Yes,
		modals: Status.Yes,
		permsv2: Status.Yes,
		automod: Status.No,
		localization: Status.Yes,
		forums: Status.No
	},
	{
		name: 'Discall',
		url: 'https://github.com/Discall-Development/Discall',
		language: 'JavaScript',
		apiVer: 10,
		gwVer: 10,
		slashCommands: Status.No,
		buttons: Status.No,
		selectMenus: Status.No,
		threads: Status.Yes,
		guildStickers: Status.No,
		contextMenus: Status.No,
		autocomplete: Status.No,
		scheduledEvents: Status.No,
		timeouts: Status.No,
		modals: Status.No,
		permsv2: Status.No,
		automod: Status.Yes,
		localization: Status.No,
		forums: Status.Partial
	},
	{
		name: 'Discord.jl',
		url: 'https://github.com/Xh4H/Discord.jl',
		language: 'Julia',
		apiVer: 6,
		gwVer: 6,
		slashCommands: Status.No,
		buttons: Status.No,
		selectMenus: Status.No,
		threads: Status.No,
		guildStickers: Status.No,
		contextMenus: Status.No,
		autocomplete: Status.No,
		scheduledEvents: Status.No,
		timeouts: Status.No,
		modals: Status.No,
		permsv2: Status.No,
		automod: Status.No,
		localization: Status.No,
		forums: Status.No
	},
	{
		name: 'Kord',
		url: 'https://github.com/kordlib/kord',
		language: 'Kotlin',
		apiVer: 10,
		gwVer: 10,
		slashCommands: Status.Yes,
		buttons: Status.Yes,
		selectMenus: Status.Yes,
		threads: Status.Yes,
		guildStickers: Status.Yes,
		contextMenus: Status.Yes,
		autocomplete: Status.Yes,
		scheduledEvents: Status.Yes,
		timeouts: Status.Yes,
		modals: Status.Yes,
		permsv2: Status.Yes,
		automod: Status.Yes,
		localization: Status.Yes,
		forums: Status.Yes
	},
	{
		name: 'Discordia',
		url: 'https://github.com/SinisterRectus/Discordia',
		language: 'Lua',
		apiVer: 8,
		gwVer: 8,
		slashCommands: Status.No,
		buttons: Status.No,
		selectMenus: Status.No,
		threads: Status.No,
		guildStickers: Status.No,
		contextMenus: Status.No,
		autocomplete: Status.No,
		scheduledEvents: Status.No,
		timeouts: Status.Yes,
		modals: Status.No,
		permsv2: Status.No,
		automod: Status.No,
		localization: Status.No,
		forums: Status.No
	},
	{
		name: 'Dimscord',
		url: 'https://github.com/krisppurg/dimscord',
		language: 'Nim',
		apiVer: 10,
		gwVer: 10,
		slashCommands: Status.Yes,
		buttons: Status.Yes,
		selectMenus: Status.Partial,
		threads: Status.Yes,
		guildStickers: Status.Yes,
		contextMenus: Status.Yes,
		autocomplete: Status.Yes,
		scheduledEvents: Status.Yes,
		timeouts: Status.Yes,
		modals: Status.Yes,
		permsv2: Status.Yes,
		automod: Status.Yes,
		localization: Status.Yes,
		forums: Status.Partial
	},
	{
		name: 'DiscordPHP',
		url: 'https://github.com/discord-php/DiscordPHP',
		language: 'PHP',
		apiVer: [9, 10],
		gwVer: [9, 10],
		slashCommands: Status.Yes,
		buttons: Status.Yes,
		selectMenus: Status.Partial,
		threads: Status.Yes,
		guildStickers: Status.Yes,
		contextMenus: Status.Yes,
		autocomplete: Status.Yes,
		scheduledEvents: Status.Yes,
		timeouts: Status.Yes,
		modals: Status.Yes,
		permsv2: Status.Yes,
		automod: Status.Yes,
		localization: Status.Yes,
		forums: Status.InDev
	},
	{
		name: 'RestCord',
		url: 'https://github.com/restcord/restcord',
		language: 'PHP',
		apiVer: [6, 9],
		gwVer: null,
		slashCommands: Status.No,
		buttons: Status.No,
		selectMenus: Status.No,
		threads: Status.InDev,
		guildStickers: Status.No,
		contextMenus: Status.No,
		autocomplete: Status.No,
		scheduledEvents: [Status.PR, "https://github.com/restcord/restcord/pull/166"],
		timeouts: Status.No,
		modals: Status.No,
		permsv2: Status.No,
		automod: Status.No,
		localization: Status.No,
		forums: Status.No
	},
	{
		name: 'discord.py',
		url: 'https://github.com/Rapptz/discord.py',
		language: 'Python',
		apiVer: 10,
		gwVer: 10,
		slashCommands: Status.Yes,
		buttons: Status.Yes,
		selectMenus: Status.Yes,
		threads: Status.Yes,
		guildStickers: Status.Yes,
		contextMenus: Status.Yes,
		autocomplete: Status.Yes,
		scheduledEvents: Status.Yes,
		timeouts: Status.Yes,
		modals: Status.Yes,
		permsv2: Status.Yes,
		automod: Status.Yes,
		localization: Status.Yes,
		forums: Status.Yes
	},
	{
		name: 'disnake 🍴',
		url: 'https://github.com/DisnakeDev/disnake',
		language: 'Python',
		apiVer: 10,
		gwVer: 10,
		slashCommands: Status.Yes,
		buttons: Status.Yes,
		selectMenus: Status.Yes,
		threads: Status.Yes,
		guildStickers: Status.Yes,
		contextMenus: Status.Yes,
		autocomplete: Status.Yes,
		scheduledEvents: Status.Yes,
		timeouts: Status.Yes,
		modals: Status.Yes,
		permsv2: Status.Yes,
		automod: Status.Yes,
		localization: Status.Yes,
		forums: Status.Yes
	},
	{
		name: 'enhanced-discord.py 🍴🪦',
		url: 'https://github.com/iDevision/enhanced-discord.py',
		language: 'Python',
		apiVer: 8,
		gwVer: 9,
		slashCommands: Status.Yes,
		buttons: Status.Yes,
		selectMenus: Status.Partial,
		threads: Status.Yes,
		guildStickers: Status.Yes,
		contextMenus: Status.No,
		autocomplete: Status.Yes,
		scheduledEvents: Status.No,
		timeouts: Status.Yes,
		modals: Status.Yes,
		permsv2: Status.No,
		automod: Status.No,
		localization: Status.No,
		forums: Status.No
	},
	{
		name: 'hata',
		url: 'https://github.com/HuyaneMatsu/hata',
		language: 'Python',
		apiVer: 10,
		gwVer: 10,
		slashCommands: Status.Yes,
		buttons: Status.Yes,
		selectMenus: Status.Yes,
		threads: Status.Yes,
		guildStickers: Status.Yes,
		contextMenus: Status.Yes,
		autocomplete: Status.Yes,
		scheduledEvents: Status.Yes,
		timeouts: Status.Yes,
		modals: Status.Yes,
		permsv2: Status.Yes,
		automod: Status.Yes,
		localization: Status.Yes,
		forums: Status.Yes
	},
	{
		name: 'hikari',
		url: 'https://github.com/hikari-py/hikari',
		language: 'Python',
		apiVer: 10,
		gwVer: 10,
		slashCommands: Status.Yes,
		buttons: Status.Yes,
		selectMenus: Status.Yes,
		threads: Status.Yes,
		guildStickers: Status.Yes,
		contextMenus: Status.Yes,
		autocomplete: Status.Yes,
		scheduledEvents: Status.Yes,
		timeouts: Status.Yes,
		modals: Status.Yes,
		permsv2: Status.Yes,
		automod: [Status.PR, "https://github.com/hikari-py/hikari/pull/1220"],
		localization: Status.Yes,
		forums: Status.Yes
	},
	{
		name: 'interactions.py',
		url: 'https://github.com/interactions-py/library',
		language: 'Python',
		apiVer: 10,
		gwVer: 10,
		slashCommands: Status.Yes,
		buttons: Status.Yes,
		selectMenus: Status.Yes,
		threads: Status.Yes,
		guildStickers: Status.Yes,
		contextMenus: Status.Yes,
		autocomplete: Status.Yes,
		scheduledEvents: Status.Yes,
		timeouts: Status.Yes,
		modals: Status.Yes,
		permsv2: Status.Yes,
		automod: Status.Yes,
		localization: Status.Yes,
		forums: Status.Yes
	},
	{
		name: 'NAFF 🪦',
		url: 'https://github.com/NAFTeam/NAFF',
		language: 'Python',
		apiVer: 10,
		gwVer: 10,
		slashCommands: Status.Yes,
		buttons: Status.Yes,
		selectMenus: Status.Yes,
		threads: Status.Yes,
		guildStickers: Status.Yes,
		contextMenus: Status.Yes,
		autocomplete: Status.Yes,
		scheduledEvents: Status.Yes,
		timeouts: Status.Yes,
		modals: Status.Yes,
		permsv2: Status.Yes,
		automod: Status.Yes,
		localization: Status.Yes,
		forums: Status.Yes
	},
	{
		name: 'nextcord 🍴',
		url: 'https://github.com/nextcord/nextcord',
		language: 'Python',
		apiVer: 10,
		gwVer: 10,
		slashCommands: Status.Yes,
		buttons: Status.Yes,
		selectMenus: Status.Yes,
		threads: Status.Yes,
		guildStickers: Status.Yes,
		contextMenus: Status.Yes,
		autocomplete: Status.Yes,
		scheduledEvents: Status.Yes,
		timeouts: Status.Yes,
		modals: Status.Yes,
		permsv2: Status.Yes,
		automod: Status.Yes,
		localization: Status.Yes,
		forums: Status.Yes
	},
	{
		name: 'pycord 🍴',
		url: 'https://github.com/Pycord-Development/pycord',
		language: 'Python',
		apiVer: 10,
		gwVer: 10,
		slashCommands: Status.Yes,
		buttons: Status.Yes,
		selectMenus: Status.Yes,
		threads: Status.Yes,
		guildStickers: Status.Yes,
		contextMenus: Status.Yes,
		autocomplete: Status.Yes,
		scheduledEvents: Status.Yes,
		timeouts: Status.Yes,
		modals: Status.Yes,
		permsv2: Status.Yes,
		automod: Status.Yes,
		localization: Status.Yes,
		forums: Status.Yes
	},
	{
		name: 'discorb',
		url: 'https://github.com/discorb-lib/discorb',
		language: 'Ruby',
		apiVer: 10,
		gwVer: 10,
		slashCommands: Status.Yes,
		buttons: Status.Yes,
		selectMenus: Status.Partial,
		threads: Status.Yes,
		guildStickers: Status.Yes,
		contextMenus: Status.Yes,
		autocomplete: Status.Yes,
		scheduledEvents: Status.Yes,
		timeouts: Status.Yes,
		modals: Status.Yes,
		permsv2: Status.Yes,
		automod: Status.Yes,
		localization: Status.Yes,
		forums: Status.No
	},
	{
		name: 'discordrb',
		url: 'https://github.com/shardlab/discordrb',
		language: 'Ruby',
		apiVer: [6, 9],
		gwVer: [6, 9],
		slashCommands: Status.InDev,
		buttons: Status.InDev,
		selectMenus: Status.PartialDev,
		threads: Status.InDev,
		guildStickers: Status.InDev,
		contextMenus: Status.InDev,
		autocomplete: Status.No,
		scheduledEvents: Status.No,
		timeouts: Status.InDev,
		modals: Status.InDev,
		permsv2: Status.No,
		automod: Status.No,
		localization: [Status.PR, "https://github.com/shardlab/discordrb/pull/190"],
		forums: Status.No
	},
	{
		name: 'discord-rs',
		url: 'https://github.com/SpaceManiac/discord-rs',
		language: 'Rust',
		apiVer: 6,
		gwVer: 6,
		slashCommands: Status.No,
		buttons: Status.No,
		selectMenus: Status.No,
		threads: Status.No,
		guildStickers: Status.No,
		contextMenus: Status.No,
		autocomplete: Status.No,
		scheduledEvents: Status.No,
		timeouts: Status.No,
		modals: Status.No,
		permsv2: Status.No,
		automod: Status.No,
		localization: Status.No,
		forums: Status.No
	},
	{
		name: 'Serenity',
		url: 'https://github.com/serenity-rs/serenity',
		language: 'Rust',
		apiVer: 10,
		gwVer: 10,
		slashCommands: Status.Yes,
		buttons: Status.Yes,
		selectMenus: Status.Partial,
		threads: Status.Yes,
		guildStickers: Status.Yes,
		contextMenus: Status.Yes,
		autocomplete: Status.Yes,
		scheduledEvents: Status.Yes,
		timeouts: Status.Yes,
		modals: Status.Yes,
		permsv2: Status.Yes,
		automod: Status.Yes,
		localization: Status.Yes,
		forums: Status.Partial
	},
	{
		name: 'Twilight',
		url: 'https://github.com/twilight-rs/twilight',
		language: 'Rust',
		apiVer: 10,
		gwVer: 10,
		slashCommands: Status.Yes,
		buttons: Status.Yes,
		selectMenus: Status.Partial,
		threads: Status.Yes,
		guildStickers: Status.Yes,
		contextMenus: Status.Yes,
		autocomplete: Status.Yes,
		scheduledEvents: Status.Yes,
		timeouts: Status.Yes,
		modals: Status.Yes,
		permsv2: Status.Yes,
		automod: Status.Yes,
		localization: Status.Yes,
		forums: Status.Yes
	},
	{
		name: 'AckCord',
		url: 'https://github.com/Katrix/AckCord',
		language: 'Scala',
		apiVer: 9,
		gwVer: 9,
		slashCommands: Status.Yes,
		buttons: Status.Yes,
		selectMenus: Status.Partial,
		threads: Status.Yes,
		guildStickers: Status.Yes,
		contextMenus: Status.Yes,
		autocomplete: Status.Yes,
		scheduledEvents: Status.Yes,
		timeouts: Status.Yes,
		modals: [Status.PR, "https://github.com/Katrix/AckCord/pull/69"],
		permsv2: Status.No,
		automod: Status.No,
		localization: Status.No,
		forums: Status.No
	},
	{
		name: 'DiscordBM',
		url: 'https://github.com/DiscordBM/DiscordBM',
		language: 'Swift',
		apiVer: 10,
		gwVer: 10,
		slashCommands: Status.Yes,
		buttons: Status.Yes,
		selectMenus: Status.Yes,
		threads: Status.Yes,
		guildStickers: Status.Yes,
		contextMenus: Status.Yes,
		autocomplete: Status.Yes,
		scheduledEvents: Status.Yes,
		timeouts: Status.Yes,
		modals: Status.Yes,
		permsv2: Status.Yes,
		automod: Status.Yes,
		localization: Status.Yes,
		forums: Status.Yes
	},
	{
		name: 'Swiftcord 🍴',
		url: 'https://github.com/SketchMaster2001/Swiftcord',
		language: 'Swift',
		apiVer: 9,
		gwVer: 9,
		slashCommands: Status.Yes,
		buttons: Status.Yes,
		selectMenus: Status.Partial,
		threads: Status.Yes,
		guildStickers: Status.Yes,
		contextMenus: Status.Yes,
		autocomplete: Status.Yes,
		scheduledEvents: Status.Yes,
		timeouts: Status.Yes,
		modals: Status.Yes,
		permsv2: Status.InDev,
		automod: Status.No,
		localization: Status.InDev,
		forums: Status.No
	},
	{
		name: 'SwiftDiscord',
		url: 'https://github.com/nuclearace/SwiftDiscord',
		language: 'Swift',
		apiVer: [6, 8],
		gwVer: [6, 8],
		slashCommands: Status.InDev,
		buttons: Status.InDev,
		selectMenus: Status.No,
		threads: Status.No,
		guildStickers: Status.No,
		contextMenus: Status.No,
		autocomplete: Status.No,
		scheduledEvents: Status.No,
		timeouts: Status.No,
		modals: Status.No,
		permsv2: Status.No,
		automod: Status.No,
		localization: Status.No,
		forums: Status.No
	}
]
